export const API = {
  auth: {
    register:              '/auth/register',
    login:                 '/auth/login',
    refresh:               '/auth/refresh',
    logout:                '/auth/logout',
    logoutAll:             '/auth/logout-all',
    me:                    '/auth/me',
    sessions:              '/auth/sessions',
    session:               (id: string) => `/auth/sessions/${id}`,
    forgotPassword:        '/auth/forgot-password',
    resetPassword:         '/auth/reset-password',
    confirmEmail:          '/auth/confirm-email',
    sendConfirmationEmail: '/auth/send-confirmation-email',
    changePassword:        '/auth/change-password',
  },
  companies: {
    list:              '/companies',
    create:            '/companies',
    detail:            (id: string) => `/companies/${id}`,
    update:            (id: string) => `/companies/${id}`,
    members:           (id: string) => `/companies/${id}/members`,
    member:            (id: string, userId: string) => `/companies/${id}/members/${userId}`,
    transferOwnership: (id: string) => `/companies/${id}/transfer-ownership`,
  },
  employees: {
    list:      (cid: string) => `/companies/${cid}/employees`,
    create:    (cid: string) => `/companies/${cid}/employees`,
    detail:    (cid: string, eid: string) => `/companies/${cid}/employees/${eid}`,
    update:    (cid: string, eid: string) => `/companies/${cid}/employees/${eid}`,
    terminate: (cid: string, eid: string) => `/companies/${cid}/employees/${eid}/terminate`,
  },
  contracts: {
    list:     (cid: string, eid: string) => `/companies/${cid}/employees/${eid}/contracts`,
    create:   (cid: string, eid: string) => `/companies/${cid}/employees/${eid}/contracts`,
    update:   (cid: string, eid: string, ctid: string) => `/companies/${cid}/employees/${eid}/contracts/${ctid}`,
    schedule: (cid: string, eid: string, ctid: string) => `/companies/${cid}/employees/${eid}/contracts/${ctid}/schedule`,
  },
  attendance: {
    list:   (cid: string) => `/companies/${cid}/attendance`,
    create: (cid: string) => `/companies/${cid}/attendance`,
    update: (cid: string, id: string) => `/companies/${cid}/attendance/${id}`,
    delete: (cid: string, id: string) => `/companies/${cid}/attendance/${id}`,
  },
  overtime: {
    list:   (cid: string) => `/companies/${cid}/overtime`,
    create: (cid: string) => `/companies/${cid}/overtime`,
    update: (cid: string, id: string) => `/companies/${cid}/overtime/${id}`,
    delete: (cid: string, id: string) => `/companies/${cid}/overtime/${id}`,
  },
  holidays: {
    list:   (cid: string) => `/companies/${cid}/holidays`,
    create: (cid: string) => `/companies/${cid}/holidays`,
    update: (cid: string, id: string) => `/companies/${cid}/holidays/${id}`,
    delete: (cid: string, id: string) => `/companies/${cid}/holidays/${id}`,
  },
  concepts: {
    list:   (cid: string) => `/companies/${cid}/concepts`,
    detail: (cid: string, id: string) => `/companies/${cid}/concepts/${id}`,
    create: (cid: string) => `/companies/${cid}/concepts`,
    update: (cid: string, id: string) => `/companies/${cid}/concepts/${id}`,
    delete: (cid: string, id: string) => `/companies/${cid}/concepts/${id}`,
  },
  payroll: {
    periods:   (cid: string) => `/companies/${cid}/payroll/periods`,
    period:    (cid: string, pid: string) => `/companies/${cid}/payroll/periods/${pid}`,
    runs:      (cid: string) => `/companies/${cid}/payroll/runs`,
    run:       (cid: string, rid: string) => `/companies/${cid}/payroll/runs/${rid}`,
    calculate: (cid: string, rid: string) => `/companies/${cid}/payroll/runs/${rid}/calculate`,
    close:     (cid: string, rid: string) => `/companies/${cid}/payroll/runs/${rid}/close`,
    payslips:  (cid: string, rid: string) => `/companies/${cid}/payroll/runs/${rid}/payslips`,
    payslip:   (cid: string, rid: string, pid: string) => `/companies/${cid}/payroll/runs/${rid}/payslips/${pid}`,
    patchLine: (cid: string, rid: string, pid: string, lid: string) => `/companies/${cid}/payroll/runs/${rid}/payslips/${pid}/lines/${lid}`,
    exportCsv: (cid: string, rid: string) => `/companies/${cid}/payroll/runs/${rid}/payslips/export`,
  },
} as const;
