export const API = {
  auth: {
    register:              '/auth/register',
    login:                 '/auth/login',
    refresh:               '/auth/refresh',
    logout:                '/auth/logout',
    logoutAll:             '/auth/logout-all',
    me:                    '/auth/me',
    sessions:              '/auth/sessions',
    session:               (id: string) => `/auth/sessions/${id}`,
    forgotPassword:        '/auth/forgot-password',
    resetPassword:         '/auth/reset-password',
    confirmEmail:          '/auth/confirm-email',
    sendConfirmationEmail: '/auth/send-confirmation-email',
    changePassword:        '/auth/change-password',
    locale:                '/auth/locale',
  },
  companies: {
    list:              '/companies',
    create:            '/companies',
    detail:            (id: string) => `/companies/${id}`,
    update:            (id: string) => `/companies/${id}`,
    members:           (id: string) => `/companies/${id}/members`,
    member:            (id: string, userId: string) => `/companies/${id}/members/${userId}`,
    leaveCompany:      (id: string) => `/companies/${id}/members/me`,
    transferOwnership: (id: string) => `/companies/${id}/transfer-ownership`,
  },
  employees: {
    list:           (cid: string) => `/companies/${cid}/employees`,
    create:         (cid: string) => `/companies/${cid}/employees`,
    detail:         (cid: string, eid: string) => `/companies/${cid}/employees/${eid}`,
    update:         (cid: string, eid: string) => `/companies/${cid}/employees/${eid}`,
    terminate:      (cid: string, eid: string) => `/companies/${cid}/employees/${eid}/terminate`,
    importTemplate: (cid: string) => `/companies/${cid}/employees/import/template`,
    import:         (cid: string) => `/companies/${cid}/employees/import`,
  },
  contracts: {
    list:     (cid: string, eid: string) => `/companies/${cid}/employees/${eid}/contracts`,
    create:   (cid: string, eid: string) => `/companies/${cid}/employees/${eid}/contracts`,
    update:   (cid: string, eid: string, ctid: string) => `/companies/${cid}/employees/${eid}/contracts/${ctid}`,
    schedule: (cid: string, eid: string, ctid: string) => `/companies/${cid}/employees/${eid}/contracts/${ctid}/schedule`,
    concepts: (cid: string, eid: string, ctid: string) => `/companies/${cid}/employees/${eid}/contracts/${ctid}/concepts`,
    concept:  (cid: string, eid: string, ctid: string, conId: string) => `/companies/${cid}/employees/${eid}/contracts/${ctid}/concepts/${conId}`,
  },
  attendance: {
    list:           (cid: string) => `/companies/${cid}/attendance`,
    create:         (cid: string) => `/companies/${cid}/attendance`,
    update:         (cid: string, id: string) => `/companies/${cid}/attendance/${id}`,
    delete:         (cid: string, id: string) => `/companies/${cid}/attendance/${id}`,
    importTemplate: (cid: string) => `/companies/${cid}/attendance/import/template`,
    import:         (cid: string) => `/companies/${cid}/attendance/import`,
  },
  overtime: {
    list:   (cid: string) => `/companies/${cid}/overtime`,
    create: (cid: string) => `/companies/${cid}/overtime`,
    update: (cid: string, id: string) => `/companies/${cid}/overtime/${id}`,
    delete: (cid: string, id: string) => `/companies/${cid}/overtime/${id}`,
  },
  holidays: {
    list:   (cid: string) => `/companies/${cid}/holidays`,
    create: (cid: string) => `/companies/${cid}/holidays`,
    update: (cid: string, id: string) => `/companies/${cid}/holidays/${id}`,
    delete: (cid: string, id: string) => `/companies/${cid}/holidays/${id}`,
  },
  concepts: {
    list:   (cid: string) => `/companies/${cid}/concepts`,
    detail: (cid: string, id: string) => `/companies/${cid}/concepts/${id}`,
    create: (cid: string) => `/companies/${cid}/concepts`,
    update: (cid: string, id: string) => `/companies/${cid}/concepts/${id}`,
    delete:          (cid: string, id: string) => `/companies/${cid}/concepts/${id}`,
    validateFormula: (cid: string) => `/companies/${cid}/concepts/validate-formula`,
  },
  payroll: {
    periods:   (cid: string) => `/companies/${cid}/payroll/periods`,
    period:    (cid: string, pid: string) => `/companies/${cid}/payroll/periods/${pid}`,
    runs:      (cid: string) => `/companies/${cid}/payroll/runs`,
    run:       (cid: string, rid: string) => `/companies/${cid}/payroll/runs/${rid}`,
    calculate: (cid: string, rid: string) => `/companies/${cid}/payroll/runs/${rid}/calculate`,
    jobStatus: (cid: string, rid: string) => `/companies/${cid}/payroll/runs/${rid}/job-status`,
    close:     (cid: string, rid: string) => `/companies/${cid}/payroll/runs/${rid}/close`,
    payslips:  (cid: string, rid: string) => `/companies/${cid}/payroll/runs/${rid}/payslips`,
    payslip:   (cid: string, rid: string, pid: string) => `/companies/${cid}/payroll/runs/${rid}/payslips/${pid}`,
    patchLine: (cid: string, rid: string, pid: string, lid: string) => `/companies/${cid}/payroll/runs/${rid}/payslips/${pid}/lines/${lid}`,
    exportCsv:   (cid: string, rid: string) => `/companies/${cid}/payroll/runs/${rid}/payslips/export`,
    signatures:  (cid: string, rid: string) => `/companies/${cid}/payroll/runs/${rid}/payslips/signatures`,
    exportPdf:   (cid: string, rid: string) => `/companies/${cid}/payroll/runs/${rid}/payslips/export-pdf`,
    payslipPdf:  (cid: string, rid: string, pid: string) => `/companies/${cid}/payroll/runs/${rid}/payslips/${pid}/export-pdf`,
    crossRunPayslips: (cid: string) => `/companies/${cid}/payroll/payslips`,
  },
  myPayslips: {
    list:   (cid: string) => `/companies/${cid}/my-payslips`,
    detail: (cid: string, pid: string) => `/companies/${cid}/my-payslips/${pid}`,
    sign:   (cid: string, pid: string) => `/companies/${cid}/my-payslips/${pid}/sign`,
  },
  settlements: {
    config:     (cid: string) => `/companies/${cid}/settlement-config`,
    create:     (cid: string, eid: string) => `/companies/${cid}/employees/${eid}/settlement`,
    detail:     (cid: string, eid: string) => `/companies/${cid}/employees/${eid}/settlement`,
  },
  convenios: {
    // Company-scoped
    list:          (cid: string) => `/companies/${cid}/convenios`,
    expiring:      (cid: string) => `/companies/${cid}/convenios/expiring`,
    create:        (cid: string) => `/companies/${cid}/convenios`,
    update:        (cid: string, id: string) => `/companies/${cid}/convenios/${id}`,
    delete:        (cid: string, id: string) => `/companies/${cid}/convenios/${id}`,
    clone:         (cid: string, id: string) => `/companies/${cid}/convenios/${id}/clone`,
    addCategory:   (cid: string, id: string) => `/companies/${cid}/convenios/${id}/categories`,
    updateCategory:(cid: string, catId: string) => `/companies/${cid}/convenios/categories/${catId}`,
    deleteCategory:(cid: string, catId: string) => `/companies/${cid}/convenios/categories/${catId}`,
    // Upload (AI extraction)
    upload:            (cid: string) => `/companies/${cid}/convenios/upload`,
    confirmUpload:     (cid: string) => `/companies/${cid}/convenios/confirm-upload`,
    deleteUploadedFile:(cid: string, filename: string) => `/companies/${cid}/convenios/uploaded-file/${filename}`,
    // Assign to employee
    assign:        (cid: string, eid: string) => `/companies/${cid}/employees/${eid}/convenio`,
  },
  unions: {
    list:         (cid: string) => `/companies/${cid}/unions`,
    create:       (cid: string) => `/companies/${cid}/unions`,
    detail:       (cid: string, id: string) => `/companies/${cid}/unions/${id}`,
    update:       (cid: string, id: string) => `/companies/${cid}/unions/${id}`,
    delete:       (cid: string, id: string) => `/companies/${cid}/unions/${id}`,
    dashboard:    (cid: string) => `/companies/${cid}/unions/dashboard`,
    members:      (cid: string, id: string) => `/companies/${cid}/unions/${id}/members`,
    addMember:    (cid: string, id: string) => `/companies/${cid}/unions/${id}/members`,
    removeMember: (cid: string, id: string, mid: string) => `/companies/${cid}/unions/${id}/members/${mid}`,
  },
  auditLogs: {
    list: (cid: string) => `/companies/${cid}/audit-logs`,
  },
  admin: {
    dashboard:     '/admin/dashboard',
    companies:     '/admin/companies',
    plans:         '/admin/plans',
    plan:          (id: string) => `/admin/plans/${id}`,
    subscriptions: '/admin/subscriptions',
    subscription:  (id: string) => `/admin/subscriptions/${id}`,
    payments:      (subId: string) => `/admin/subscriptions/${subId}/payments`,
    payment:       (subId: string, payId: string) => `/admin/subscriptions/${subId}/payments/${payId}`,
    backups:       '/admin/backups',
  },
  plans: {
    list: '/plans',
  },
  companySubscription: {
    detail:        (cid: string) => `/companies/${cid}/subscription`,
    payments:      (cid: string) => `/companies/${cid}/subscription/payments`,
    paymentProof:  (cid: string) => `/companies/${cid}/subscription/payment-proof`,
    paymentProofs: (cid: string) => `/companies/${cid}/subscription/payment-proof`,
  },
  adminConvenios: {
    list:           '/admin/convenios',
    create:         '/admin/convenios',
    update:         (id: string) => `/admin/convenios/${id}`,
    delete:         (id: string) => `/admin/convenios/${id}`,
    addCategory:    (id: string) => `/admin/convenios/${id}/categories`,
    updateCategory: (catId: string) => `/admin/convenios/categories/${catId}`,
    deleteCategory: (catId: string) => `/admin/convenios/categories/${catId}`,
  },
} as const;
